/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.iia.MegaCasting;

import fr.iia.Class.Adresse;
import fr.iia.Class.Annonceur;
import fr.iia.Class.Contrat;
import fr.iia.Class.Diffuseur;
import fr.iia.Class.Domaine;
import fr.iia.Class.Media;
import fr.iia.Class.Metier;
import fr.iia.Class.Offre;
import fr.iia.DAO.OffreDAO;
import java.sql.Connection;

/**
 *
 * @author Flo
 */
public class ajouterOffre extends javax.swing.JFrame {
    private Domaine domaine;
    private String libelle;
    private String nom;
    private String mail;
    private String numeroTel;
    private Adresse adresse;
    private Media media;
    private int numero;
    private String codePostal;
    private String rue;
    private String ville;
    private Connection cnx;
    private String reference;
    private String localisation;

    /**
     * Creates new form ajouterOffre
     */
    public ajouterOffre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boutonEnregistrer = new javax.swing.JButton();
        titreBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionBox = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        profilBox = new javax.swing.JTextArea();
        dureeContratBox = new javax.swing.JTextField();
        typeContratBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nouvelle offre");

        boutonEnregistrer.setText("Enregistrer");
        boutonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEnregistrerActionPerformed(evt);
            }
        });

        titreBox.setText("Titre");

        descriptionBox.setColumns(20);
        descriptionBox.setRows(5);
        descriptionBox.setText("Description de l'offre");
        jScrollPane1.setViewportView(descriptionBox);

        profilBox.setColumns(20);
        profilBox.setRows(5);
        profilBox.setText("Profil recherché");
        jScrollPane2.setViewportView(profilBox);

        dureeContratBox.setText("Durée du contrat");
        dureeContratBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dureeContratBoxActionPerformed(evt);
            }
        });

        typeContratBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeContratBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeContratBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(boutonEnregistrer)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(titreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dureeContratBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeContratBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(titreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(typeContratBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(dureeContratBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(boutonEnregistrer))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEnregistrerActionPerformed
        String titre = titreBox.getText();
        String description = descriptionBox.getText();
        String profil = profilBox.getText();
        //int dureeContrat = (int) dureeContratBox.getValue();
        
        Offre offre = OffreDAO.trouver(cnx, reference);
        
        if (offre == null) {
            Contrat contrat = new Contrat(libelle);
            Annonceur annonceur = new Annonceur(nom, mail, numeroTel, adresse, media);
            //Diffuseur diffuseur = new Diffuseur(nom, mail, numeroTel, adresse, media);
            Metier metier = new Metier(libelle, domaine);
            //offre = new Offre(titre, reference, date_debut_publi, fin_publi, nbr_poste, description_poste, description_profil, int telephone, Contrat, Annonceur, Diffuseur, Metier);
            
            try{
               //OffreDAO.creer(cnx, off, ann, cont, dif, met);
            
            }catch (Exception ex){
                ex.printStackTrace();
            }
        }else{
            offre.setTitre(titre);
            offre.setDescription_poste(description);
            offre.setDescription_profil(profil);
        
            Contrat contrat = offre.getContrat();
            contrat.setLibelle(libelle);
                    
            Annonceur annonceur = offre.getAnnonceur();
            annonceur.setNom(nom);
            annonceur.setMail(mail);
            annonceur.setNumeroTel(numeroTel);
            annonceur.setAdresse(adresse);
            annonceur.setMedia(media);
            
            Adresse adresse = annonceur.getAdresse();
            adresse.setNumero(numero);
            adresse.setCodePostal(codePostal);
            adresse.setRue(rue);            
            adresse.setVille(ville);
            adresse.setLocalisation(localisation);
            
            Diffuseur diffuseur = offre.getDiffuseur();
            diffuseur.setNom(nom);
            diffuseur.setMail(mail);
            diffuseur.setNumeroTel(numeroTel);
            diffuseur.setAdresse(adresse);
            diffuseur.setMedia(media); 
            
            adresse = diffuseur.getAdresse();
            adresse.setNumero(numero);
            adresse.setCodePostal(codePostal);
            adresse.setRue(rue);            
            adresse.setVille(ville);
            String localisation;
            //adresse.setLocalisation(localisation);
           
            Metier metier = offre.getMetier();
            metier.setLibelle(libelle);
            metier.setDomaine(domaine);
            
            Domaine domaine = metier.getDomaine();
            domaine.setLibelle(libelle);
                       
            try {
                OffreDAO.modifier(cnx, offre);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_boutonEnregistrerActionPerformed

    private void dureeContratBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dureeContratBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dureeContratBoxActionPerformed

    private void typeContratBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeContratBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeContratBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterOffre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonEnregistrer;
    private javax.swing.JTextArea descriptionBox;
    private javax.swing.JTextField dureeContratBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea profilBox;
    private javax.swing.JTextField titreBox;
    private javax.swing.JComboBox typeContratBox;
    // End of variables declaration//GEN-END:variables
}
