/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.iia.MegaCasting;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import fr.iia.Class.Adresse;
import fr.iia.Class.Annonceur;
import fr.iia.Class.Contrat;
import fr.iia.Class.Diffuseur;
import fr.iia.Class.Domaine;
import fr.iia.Class.Media;
import fr.iia.Class.Metier;
import fr.iia.Class.Offre;
import fr.iia.Connection.JavaConnect;
import fr.iia.DAO.AnnonceursDAO;
import fr.iia.DAO.ContratDAO;
import fr.iia.DAO.DiffuseursDAO;
import fr.iia.DAO.MetierDAO;
import fr.iia.DAO.OffreDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.ZonedDateTime;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Flo
 */
public class ajouterOffre extends javax.swing.JFrame {
    Connection cnx = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form ajouterOffre
     */
    public ajouterOffre() {
        initComponents();
        JavaConnect.ImportDriver();
        cnx = JavaConnect.ConnectDB();
        diffuseurBoxActionPerformed(null);
        annonceurBoxActionPerformed(null);
        metierBoxActionPerformed(null);
        contratBoxActionPerformed(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        boutonEnregistrer = new javax.swing.JButton();
        titreBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionBox = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        profilBox = new javax.swing.JTextArea();
        dureeContratBox = new javax.swing.JTextField();
        referenceBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombrePosteBox = new javax.swing.JTextField();
        contratBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        annonceurBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        diffuseurBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        metierBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nouvelle offre");

        boutonEnregistrer.setText("Enregistrer");
        boutonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEnregistrerActionPerformed(evt);
            }
        });

        titreBox.setText("Titre");

        descriptionBox.setColumns(20);
        descriptionBox.setRows(5);
        descriptionBox.setText("Description de l offre");
        jScrollPane1.setViewportView(descriptionBox);

        profilBox.setColumns(20);
        profilBox.setRows(5);
        profilBox.setText("Profil recherché");
        jScrollPane2.setViewportView(profilBox);

        dureeContratBox.setText("Durée du contrat");
        dureeContratBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dureeContratBoxActionPerformed(evt);
            }
        });

        referenceBox.setText("reference");
        referenceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("nombrePoste");

        nombrePosteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePosteBoxActionPerformed(evt);
            }
        });

        contratBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Contrat");

        annonceurBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annonceurBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Annonceur");

        diffuseurBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffuseurBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Diffuseur");

        metierBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metierBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Metier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(referenceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dureeContratBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(150, 150, 150))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addGap(53, 53, 53)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(74, 74, 74)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrePosteBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(diffuseurBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contratBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(annonceurBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(metierBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(boutonEnregistrer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(nombrePosteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contratBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(annonceurBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(diffuseurBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(metierBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dureeContratBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonEnregistrer))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void boutonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEnregistrerActionPerformed
        String titre = titreBox.getText();
        String reference = referenceBox.getText();
        
        Date d = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String dateDebutPubli = dateFormat.format(d);
        
        Date dFin = new Date(); 
        dFin.setMonth(d.getMonth()+2);
        DateFormat dateFormat2 = new SimpleDateFormat("dd/MM/yyyy");
        String dateFinPubli = dateFormat.format(dFin);
        
        String description = descriptionBox.getText();
        String profil = profilBox.getText();
        int nombrePoste = Integer.parseInt(nombrePosteBox.getText());
        int dureeContrat = Integer.parseInt(dureeContratBox.getText());
        
        String libelleContrat = (String)contratBox.getSelectedItem();
        String libelleMetier = (String)metierBox.getSelectedItem();
        String nomAnnonceur = (String)annonceurBox.getSelectedItem();
        String nomDiffuseur = (String)diffuseurBox.getSelectedItem();
        
        ContratDAO contratDAO = new ContratDAO();
        MetierDAO metierDAO = new MetierDAO();
        AnnonceursDAO annonceurDAO = new AnnonceursDAO();
        DiffuseursDAO diffuseurDAO = new DiffuseursDAO();
        
        Offre offre = OffreDAO.trouver(cnx, reference);
        
        if (offre == null) {
            Contrat contrat = ContratDAO.trouver(cnx, libelleContrat);
            Metier metier = MetierDAO.trouver(cnx, libelleMetier);
            Annonceur annonceur = AnnonceursDAO.trouver(cnx, nomAnnonceur);
            Diffuseur diffuseur = DiffuseursDAO.trouver(cnx, nomDiffuseur);

            offre = new Offre(titre, reference, dateDebutPubli, dateFinPubli, nombrePoste, description, profil, dureeContrat, contrat, annonceur, diffuseur, metier);
            
            try{
                OffreDAO.creer(cnx, offre);
                JOptionPane.showConfirmDialog(rootPane, "L'offre a bien été créée !");
            }catch (Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_boutonEnregistrerActionPerformed

    private void dureeContratBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dureeContratBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dureeContratBoxActionPerformed

    private void referenceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceBoxActionPerformed

    private void nombrePosteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePosteBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePosteBoxActionPerformed

    private void contratBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratBoxActionPerformed
        try {
            String sql = "Select libelle from contrat";
            pst = cnx.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {                
                String libelleContrat = rs.getString("libelle");
                contratBox.addItem(libelleContrat);
            }
            
        } 
        catch (Exception e) {
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_contratBoxActionPerformed

    private void diffuseurBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffuseurBoxActionPerformed
        try {
            String sql = "Select nom from diffuseur";
            pst = cnx.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {                
                String nomDiffuseur = rs.getString("nom");
                diffuseurBox.addItem(nomDiffuseur);
            }
            
        } 
        catch (Exception e) {
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_diffuseurBoxActionPerformed

    private void annonceurBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annonceurBoxActionPerformed
        try {
            String sql = "Select nom from annonceur";
            pst = cnx.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {                
                String nomAnnonceur = rs.getString("nom");
                annonceurBox.addItem(nomAnnonceur);
            }
            
        } 
        catch (Exception e) {
        
        }
    }//GEN-LAST:event_annonceurBoxActionPerformed

    private void metierBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metierBoxActionPerformed
        try {
            String sql = "Select libelle from metier";
            pst = cnx.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {                
                String libelleMetier = rs.getString("libelle");
                metierBox.addItem(libelleMetier);
            }
            
        } 
        catch (Exception e) {
        
        }
    }//GEN-LAST:event_metierBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterOffre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox annonceurBox;
    private javax.swing.JButton boutonEnregistrer;
    private javax.swing.JComboBox contratBox;
    private javax.swing.JTextArea descriptionBox;
    private javax.swing.JComboBox diffuseurBox;
    private javax.swing.JTextField dureeContratBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JComboBox metierBox;
    private javax.swing.JTextField nombrePosteBox;
    private javax.swing.JTextArea profilBox;
    private javax.swing.JTextField referenceBox;
    private javax.swing.JTextField titreBox;
    // End of variables declaration//GEN-END:variables
}
